######################################################################
##
## Filename: s6base_tb.udo
## Created on: Mon Oct 24 17:22:33 GMT Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
run -all