######################################################################
##
## Filename: block_192kHz.udo
## Created on: Wed Jan 09 22:50:45 GMT Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
