######################################################################
##
## Filename: LM4550_digital_sim.udo
## Created on: Thu Dec 27 12:01:15 GMT Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
