######################################################################
##
## Filename: my_fm_stereo.udo
## Created on: Thu Jan 10 03:05:35 GMT Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
