######################################################################
##
## Filename: s6tb.udo
## Created on: Fri Dec 14 09:27:24 GMT Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
