######################################################################
##
## Filename: seqmultNM_sat.udo
## Created on: Thu Jan 10 01:08:50 GMT Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
