######################################################################
##
## Filename: stereo_mx_fm_tb.udo
## Created on: Sun Jan 06 03:58:17 GMT Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
